### ISSUE TITLE
Is not working on Debian 10 (GNOME 3.30)

### ISSUE THREAD

**Issue by EuriNaiz** [amivaleo/Show-Desktop-Button#22]
I'm consent that the extension is not compatible with gnome 3.30, just for 3.36 but I think you could consider to port it to 3.30, so many distros and systems are still using 3.30 like gnome and other so-stables systems.

Even, Thank you for your work.

**Comment by amivaleo** [comment]
Ok, I can work on extending the compatibility.
So, the latest debian release runs on gnome 30? I consider that as the oldest gnome release this extension is going to support. ;)

**Comment by amivaleo** [comment]
I've tested the extension on gnome-shell 3.32. It works fine.

I presume it should work on gnome 3.34 too, since I already know it works on 3.36.

I need to test it on gnome-shell 3.30. Would you like to help? If you do use 3.30, you could try to install the extension from the website.

If and only if it works, I ask you to paste here the output of

`~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/metadata.json`

Thank you!

**Comment by EuriNaiz** [comment]
I'm late, sorry i haven't the time to check github.
i tried installing from the site extensions.gnome.org and cloning this git repo and it did'nt worked...

I got this with `grep "version" ~/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/metadata.json`

```
  "shell-version": [
  "version": 16
```


With this: 

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/euri/.local/share/gnome-shell/extensions/show-desktop-button@amivaleo/prefs.js:11:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:68:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

```

**Comment by amivaleo** [comment]
My apologies, I haven't checked here for a while. I'm sorry.

You could try to download version 17, edit the metadata.json file so to include your gnome version in the list after "shell-version" and check if it works after a reboot.

My understanding is that the latest stable release is Debian 11 which should come with gnome 40, for which the extension should work flawlessly.

I think older stable versions worth less care, so I'm inclined to put only a tiny effort on those. Are you still experiencing issues?

**Comment by amivaleo** [comment]
I believe this doesn't apply anymore, since version 17 of this extension is not available anymore.
